In [1]:
import numpy as np

In [2]:
#Los arrays en numpy son homogeneos, es decir, todos los elementos deben ser del mismo tipo
#Si se intenta crear un array con elementos de diferentes tipos, numpy los convertira a un tipo comun   
a = np.array([1,2,3])
print(a)
print(a.dtype)

a.size
a.shape

[1 2 3]
int64


(3,)

In [3]:
#matriz de 1 dimension
b = np.array([1,2,3], dtype = float)
print(b)

#matriz de 2 dimensiones
c = np.array([[1,2,3],[4,5,6]])
print(c)

[1. 2. 3.]
[[1 2 3]
 [4 5 6]]


In [4]:
print(c.ndim) #numero de dimensiones
print(c.shape) #forma de la matriz

2
(2, 3)


In [5]:
#Indexacion de arrays 1 dimension
print(b[2])

#Indexacion de arrays 2 dimension
print(c[1, 0]) #segunda dimension, primer elemento

3.0
4


In [6]:
c = np.size #numero de elementos de la matriz
print(np.size)

<function size at 0x0000023E7EF7BA60>


In [7]:
# Crear un array unidimensional
mi_array = np.array([1, 2, 3, 4])
print("Array unidimensional:", mi_array)

# Crear un array bidimensional (matriz)
mi_matriz = np.array([[1, 2], [3, 4]])
print("Array bidimensional:")
print(mi_matriz)


Array unidimensional: [1 2 3 4]
Array bidimensional:
[[1 2]
 [3 4]]


In [10]:
#Operaciones con arrays

# Suma elemento a elemento
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
resultado = array1 + array2
print("Suma de arrays:", resultado)

# Multiplicación elemento a elemento
resultado_mul = array1 * array2
print("Multiplicación de arrays:", resultado_mul)

# Operaciones con escalares
resultado_escalar = array1 * 3
print("Multiplicación por escalar:", resultado_escalar)


Suma de arrays: [11 22 33]
Multiplicación de arrays: [10 40 90]
Multiplicación por escalar: [30 60 90]


In [11]:
#Funciones avanzadas de numpy

# Array de ceros
array_ceros = np.zeros((2, 3))
print("Array de ceros:")
print(array_ceros)

# Array de números aleatorios
array_aleatorio = np.random.rand(3, 3)
print("Array aleatorio:")
print(array_aleatorio)

# Array con rango
array_rango = np.arange(0, 10, 2)  # Inicio: 0, Fin: 10, Paso: 2
print("Array con rango:", array_rango)


Array de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]
Array aleatorio:
[[0.84565181 0.85477315 0.63012484]
 [0.92211283 0.31967392 0.33276639]
 [0.67583765 0.47102091 0.33750496]]
Array con rango: [0 2 4 6 8]


In [12]:
#Indexación y slicing avanzado

mi_matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Seleccionar la primera fila
print("Primera fila:", mi_matriz[0])

# Seleccionar la primera columna
print("Primera columna:", mi_matriz[:, 0])

# Selección con rangos
print("Submatriz (esquinas):")
print(mi_matriz[0:2, 1:3])


Primera fila: [1 2 3]
Primera columna: [1 4 7]
Submatriz (esquinas):
[[2 3]
 [5 6]]


In [13]:
#operaciones con matrices

# Producto de matrices
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
producto = np.dot(matriz1, matriz2)
print("Producto matricial:")
print(producto)

# Transpuesta de una matriz
transpuesta = np.transpose(matriz1)
print("Transpuesta de la matriz:")
print(transpuesta)


Producto matricial:
[[19 22]
 [43 50]]
Transpuesta de la matriz:
[[1 3]
 [2 4]]


In [14]:
#Funciones matemáticas avanzadas
#NumPy tiene una amplia gama de funciones matemáticas integradas:

array = np.array([1, 2, 3, 4])

# Raíz cuadrada
print("Raíz cuadrada:", np.sqrt(array))

# Seno y coseno
print("Seno:", np.sin(array))
print("Coseno:", np.cos(array))

# Suma acumulativa
print("Suma acumulativa:", np.cumsum(array))


Raíz cuadrada: [1.         1.41421356 1.73205081 2.        ]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Coseno: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
Suma acumulativa: [ 1  3  6 10]


In [ ]:
array_con_nan = np.array([1, 2, np.nan, 4])

# Comprobar si hay NaN
print("¿Hay NaN?", np.isnan(array_con_nan))

# Reemplazar NaN por un valor
array_sin_nan = np.nan_to_num(array_con_nan, nan=0)
print("Array sin NaN:", array_sin_nan)
